
version: 2
 
models:

  - name: google_ads
    description:  Table containes data from google ads 

    columns:
      - name: platform
        description: google_ads
      - name: account_name
        description: Advertising type, as in Paid Search, Paid Social, Diplay, Video
      - name: date
        description: Digital Ads date 
      - name: campaign_name
        description: campaign name
      - name: clicks
        description: Count of times users click on a digital ad to reach the target url
      - name: impressions
        description: Count of times a digital ad is shown
      - name: conversions
        description: Orders
      - name: conversions_value
        description: Order value
      - name: spend
        description: money spent on digital Ads
      - name: interactions
        description: ""  


  - name: facebook_ads
    description: Table containes data from facebook ads 

    columns:
      - name: platform
        description: marketing platforms,  Facebook
      - name: account_name
        description: Advertising type, as in Paid Search, Paid Social, Diplay, Video
      - name: date
        description: Digital Ads date 
      - name: clicks
        description: Count of times users click on a digital ad to reach the target url
      - name: campaign_name
        description: campaign name
      - name: impressions
        description: Count of times a digital ad is shown
      - name: conversions
        description: Orders
      - name: conversions_value
        description: Order value
      - name: spend
        description: money spent on digital Ads
      - name: interactions
        description: ""    


  - name: google_dv360
    description: Table containes data from google dv360 

    columns:
      - name: platform
        description: marketing platforms,  Google DV360
      - name: advertiser
        description: Advertising type, as in Paid Search, Paid Social, Diplay, Video
      - name: date
        description: Digital Ads date 
      - name: campaign_name
        description: campaign name
      - name: clicks
        description: Count of times users click on a digital ad to reach the target url
      - name: impressions
        description: Count of times a digital ad is shown
      - name: conversions
        description: Orders
      - name: conversions_value
        description: Order value
      - name: spend
        description: money spent on digital Ads
      - name: interactions
        description: "" 
  
  - name: performance
    description: Marketing perfomance table 
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - platform
            - account_name
            - date
            - campaign_name
    columns:
      - name: platform
        description: marketing platforms, as in FB Ads, Google Ads, Google DV360
      - name: account_name
        description: Advertising type, as in Paid Search, Paid Social, Diplay, Video
      - name: date
        description: Digital Ads date 
      - name: campaign_name
        description: campaign name
      - name: clicks
        description: Count of times users click on a digital ad to reach the target url
      - name: impressions
        description: Count of times a digital ad is shown
      - name: conversions
        description: Orders
      - name: conversions_value
        description: Order value
      - name: spend
        description: money spent on digital Ads
      - name: interactions
        description: "" 

  - name: ft_abintus
    description: ""
    database: stage-landing
    tables:
      - name: abintus_hq
        description: ""
        columns:
          - name: _file
            description: ""
          - name: _line
            description: ""
          - name: _30_ta_cpp
            description: ""
          - name: _30_ta_grps_20_in_spain_
            description: ""
          - name: _fivetran_synced
            description: ""
          - name: _modified
            description: ""
          - name: ad_serving_tracking_costs_if_applicable_
            description: ""
          - name: added_value_eur_
            description: ""
          - name: affinity_index_targeting_
            description: ""
          - name: agency_client
            description: ""
          - name: agency_commission_
            description: ""
          - name: agency_fees_
            description: ""
          - name: agency_fees_local_currency_
            description: ""
          - name: average_grp_spot
            description: ""
          - name: booked_media_cost_in_000_
            description: ""
          - name: campaign
            description: ""
          - name: click_through_rate
            description: ""
          - name: copy_length
            description: ""
          - name: cost_per_cinema_site
            description: ""
          - name: cost_per_click
            description: ""
          - name: cost_per_insertion
            description: ""
          - name: cost_per_screen
            description: ""
          - name: cost_per_site_panel
            description: ""
          - name: country
            description: ""
          - name: cpm
            description: ""
          - name: direct_buy_y_n
            description: ""
          - name: end_date
            description: ""
          - name: engagement_rate
            description: ""
          - name: final_cost_to_client
            description: ""
          - name: final_cpm
            description: ""
          - name: final_gross_contacts_overall_in_mio_tg_a_14_
            description: ""
          - name: final_net_media_cost_in_000_
            description: ""
          - name: final_net_reach_in_mio_within_planned_tg_
            description: ""
          - name: frequency_ots
            description: ""
          - name: gross_negotiated_net_cost
            description: ""
          - name: impressions
            description: ""
          - name: local_currency
            description: ""
          - name: market_region
            description: ""
          - name: media_channel_level_1
            description: ""
          - name: media_channel_level_2
            description: ""
          - name: negotiated_media_discount_
            description: ""
          - name: net_cost_net_net_cost
            description: ""
          - name: no_of_days
            description: ""
          - name: number_of_clicks
            description: ""
          - name: number_of_comments
            description: ""
          - name: number_of_insertions
            description: ""
          - name: number_of_likes
            description: ""
          - name: number_of_screens
            description: ""
          - name: number_of_shares
            description: ""
          - name: number_of_sites_cinemas
            description: ""
          - name: number_of_sites_panels
            description: ""
          - name: number_of_spots_bought
            description: ""
          - name: planned_actual
            description: ""
          - name: planned_gross_contacts_overall_in_mio_tg_a_14_
            description: ""
          - name: planned_net_media_cost_in_000_
            description: ""
          - name: planned_net_reach_in_mio_planned_tg_
            description: ""
          - name: planned_target_group
            description: ""
          - name: premium_position_definitions
            description: ""
          - name: prime_time_drive_time_definition
            description: ""
          - name: production
            description: ""
          - name: production_costs_if_applicable_
            description: ""
          - name: ratecard_gross_cost
            description: ""
          - name: reach_
            description: ""
          - name: remarks_comments
            description: ""
          - name: share_of_digital
            description: ""
          - name: share_of_drive_time_from_ratings_
            description: ""
          - name: share_of_premium_positions_from_ratings_
            description: ""
          - name: share_of_prime_peak_time_from_ratings_
            description: ""
          - name: share_of_right_hand_side
            description: ""
          - name: start_date
            description: ""
          - name: ta_grps
            description: ""
          - name: ta_universe
          - name: taxes_
            description: ""
          - name: view_through_rate
            description: ""
          - name: viewability_definition
            description: ""
          - name: viewability_rate
            description: ""
          - name: viewable_impressions
            description: ""
            description: ""
          - name: views