version: 2

sources:
  - name: 'GoogleAd'
    description:  Google Ads data for more info visit  https://cloud.google.com/bigquery-transfer/docs/adwords-transformation 
    database: stage-landing
    tags: ['marketing']
    tables:
      - name: AdBasicStats_9940526481
        description: Google Ads basic perfomance report
        loaded_at_field: timestamp(date)
        freshness: 
          warn_after: {count: 2, period: day}
          error_after: {count: 5, period: day}
       
      - name: Campaign_9940526481
        description: Google ads campaigns data

      - name: AdGroup_9940526481
        description: Google ads group name data
      
      - name: Criteria_9940526481
        description: Google ads criteria_ data

      - name: Customer_9940526481
        description: Google ads customers  data
      
      - name: Keyword_9940526481
        description: Google ads keywords  data
      - name: Ad_9940526481
        description: Google ads search stats data

      - name: SearchQueryStats_9940526481
        description: Google ads search stats data
      - name: VideoBasicStats_9940526481
        description: Google ads search stats data
      - name: VideoNonClickStats_9940526481
        description: Google ads search stats data
      - name: KeywordCrossDeviceStats_9940526481
        description: Google ads search stats data

  - name: 'google_ad_fr'
    description:  Google Ads France data for more info visit  https://cloud.google.com/bigquery-transfer/docs/adwords-transformation 
    database: stage-landing
    tags: ['marketing']
    tables:
      - name: AdBasicStats_8396768808
        description: Google Ads basic perfomance report
        loaded_at_field: timestamp(date)
        freshness: 
          warn_after: {count: 2, period: day}
          error_after: {count: 5, period: day}
       
      - name: Campaign_8396768808
        description: Google ads campaigns data

      - name: AdGroup_8396768808
        description: Google ads group name data
      
      - name: Criteria_8396768808
        description: Google ads criteria_ data

      - name: Customer_8396768808
        description: Google ads customers  data
      
      - name: Keyword_8396768808
        description: Google ads keywords  data
      - name: Ad_8396768808
        description: Google ads search stats data

      - name: SearchQueryStats_8396768808
        description: Google ads search stats data
      - name: VideoBasicStats_8396768808
        description: Google ads search stats data
      - name: VideoNonClickStats_8396768808
        description: Google ads search stats data
      - name: KeywordCrossDeviceStats_8396768808
        description: Google ads search stats data

  - name: 'google_ad_sp'
    description:  Google Ads France data for more info visit  https://cloud.google.com/bigquery-transfer/docs/adwords-transformation 
    database: stage-landing
    tags: ['marketing']
    tables:
      - name: AdBasicStats_1713416990
        description: Google Ads basic perfomance report
        loaded_at_field: timestamp(date)
        freshness: 
          warn_after: {count: 2, period: day}
          error_after: {count: 5, period: day}
       
      - name: Campaign_1713416990
        description: Google ads campaigns data

      - name: AdGroup_1713416990
        description: Google ads group name data
      
      - name: Criteria_1713416990
        description: Google ads criteria_ data

      - name: Customer_1713416990
        description: Google ads customers  data
      
      - name: Keyword_1713416990
        description: Google ads keywords  data
      - name: Ad_1713416990
        description: Google ads search stats data

      - name: SearchQueryStats_1713416990
        description: Google ads search stats data
      - name: VideoBasicStats_1713416990
        description: Google ads search stats data
      - name: VideoNonClickStats_1713416990
        description: Google ads search stats data
      - name: KeywordCrossDeviceStats_1713416990
        description: Google ads search stats data

        

  - name: 'ft_facebook_ad'
    description:  Facebook ad data comes from fivetran conntion for more info visit  https://fivetran.com/docs/applications/facebook-ads#facebookads
    database: stage-landing
    tags: ['marketing']
    tables:
      - name: basic_report
        description:   Facebook ad basic perfomance report
        loaded_at_field: timestamp(date)
        freshness: 
          warn_after: {count: 2, period: day}
          error_after: {count: 5, period: day}       
      - name: basic_report_actions
        description:  facebook actions data
      - name: basic_report_action_values
        description:  facebook actions data value 
      - name: basic_report_video_p_100_watched_actions
        description:  facebook ad video info 
      - name: basic_report_video_p_75_watched_actions
        description:  facebook ad video info 
      - name: basic_report_video_p_50_watched_actions
        description:  facebook ad video info 
      - name: basic_report_video_p_25_watched_actions
        description:  facebook ad video info
      - name: basic_report_video_p_95_watched_actions
        description:  facebook ad video info
      
      - name: platform_device_click
        description:   Facebook ad basic perfomance report
        loaded_at_field: timestamp(date)
        freshness: 
          warn_after: {count: 2, period: day}
          error_after: {count: 5, period: day}       
      - name: platform_device_click_actions
        description:  facebook actions data
      - name: platform_device_click_action_values
        description:  facebook actions data value 
      - name: platform_device_click_video_p_100_watched_actions
        description:  facebook ad video info 
      - name: platform_device_click_video_p_75_watched_actions
        description:  facebook ad video info 
      - name: platform_device_click_video_p_50_watched_actions
        description:  facebook ad video info 
      - name: platform_device_click_video_p_25_watched_actions
        description:  facebook ad video info
      - name: platform_device_click_video_p_95_watched_actions
        description:  facebook ad video info

      - name: age_gender_click
        description:   Facebook ad basic perfomance report
        loaded_at_field: timestamp(date)
        freshness: 
          warn_after: {count: 2, period: day}
          error_after: {count: 5, period: day}       
      - name: age_gender_click_actions
        description:  facebook actions data
      - name: age_gender_click_action_values
        description:  facebook actions data value 
      - name: age_gender_click_video_p_100_watched_actions
        description:  facebook ad video info 
      - name: age_gender_click_video_p_75_watched_actions
        description:  facebook ad video info 
      - name: age_gender_click_video_p_50_watched_actions
        description:  facebook ad video info 
      - name: age_gender_click_video_p_25_watched_actions
        description:  facebook ad video info
      - name: age_gender_click_video_p_95_watched_actions
        description:  facebook ad video info

      - name: region_click
        description:   Facebook ad basic perfomance report
        loaded_at_field: timestamp(date)
        freshness: 
          warn_after: {count: 2, period: day}
          error_after: {count: 5, period: day}       
      - name: region_click_actions
        description:  facebook actions data
      - name: region_click_action_values
        description:  facebook actions data value 
      - name: region_click_video_p_100_watched_actions
        description:  facebook ad video info 
      - name: region_click_video_p_75_watched_actions
        description:  facebook ad video info 
      - name: region_click_video_p_50_watched_actions
        description:  facebook ad video info 
      - name: region_click_video_p_25_watched_actions
        description:  facebook ad video info
      - name: region_click_video_p_95_watched_actions
        description:  facebook ad video info

  - name: 'ft_google_display_and_video_360'
    description: google display and video data comes from fivetran conntion for more info visit https://fivetran.com/docs/applications/google-display-and-video-360 
    database: stage-landing
    tags: ['marketing']
    tables:
      - name: basic_report
        description:  google display and video basic perfomance report
        loaded_at_field: timestamp(date)
        freshness: 
          warn_after: {count: 7, period: day}
          error_after: {count: 355, period: day}

  - name: 'ft_abintus'
    description:  Google Ads data for more info visit  https://cloud.google.com/bigquery-transfer/docs/adwords-transformation 
    database: stage-landing
    tags: ['marketing']
    tables:
      - name: abintus_hq
        description: Abintue HQ marketing data  - Data collected by abintus uploaded to GCP bucket

  - name: 'upload'
    database: stage-landing
    tags: ['marketing']
    
    tables:
      - name: Google_All_Campaigns_Update

      - name: Meta_AdSet_with_Freetext

      - name: Meta_Adsets_with_extraction_of_free_text_as_Target_Group

      - name: Meta_All_Campaigns_Update
       
 