
{{ config(
    materialized='table',
    on_schema_change='fail',
    schema='sales_stg',
    labels = {'source': 'cts', 'refresh': 'daily','connection':'fivetran','type':'enrich'},
)}}


with eci as
(
 SELECT *  
   FROM {{ source( 'ft_eci','eci_tickets') }}
   --where {{ ft_filter(none) }}
),


eci_data as (
SELECT 
_file _file,
_fivetran_synced _loaded_at, 
_fivetran_synced   _last_update, 
'ECI' AS source_code,
parse_date('%Y%m%d', cast (column_0 as string)) Booking_Date, 
parse_time('%H%M%S', column_1 )  Booking_Time,
parse_date('%Y%m%d', cast (column_2 as string))  Performance_Date, 
parse_time('%H%M%S', cast(column_3 as string))  Performance_time,
--column_4 CustomerId,
column_5 Customer_first_Name,
column_6 Customer_Last_Name,
--column_7 CustomerAddress,
--column_8 CustomerCity,
--column_9  CustomerPostalCode,
--column_10 CustomerRegion,
--column_11 CustomerCountry,
--column_12 CustomerEmail,
--column_13 CustomerFixedPhone,
--column_14 CustomerMobilePhone,
--column_15 CustomerBirthday,
--column_16 CustomerSalutation,
--column_17 CustomerGender,
--column_18 CustomerOptin,
column_19 Reservation_Number,
--column_20 TicketNumber,
column_21 Order_Number,
column_22 Production_Or_Show,
column_23 Theatre ,
--column_24  TheatreLevel,
column_25 Theatre_Area,
column_26 Theatre_row,
column_27 Theatre_seat,
column_28 Discount ,
column_29 Price_Category,
column_30  Cancellation_Status,
parse_date('%Y%m%d', cast (column_31 as string))  Cancellation_Date, 
parse_time('%H%M%S', cast(column_32 as string))  Cancellation_Hour,
column_33 Channel,
column_34  Affiliate,
--column_35  DeliveryMethod,
--column_36  PrintStatus,
--column_37  PaymentStatus,
--column_38 PromotionalCode,
--column_39 PaymentTypes,
--column_40 InitialStandardPrice,
--column_41 InitialPrice,
--column_42 FullPrice,
cast( replace(column_43,',','.') as FLOAT64 )Ticket_Price,
cast( replace(column_44,',','.') as FLOAT64 ) Customer_Price,
cast( replace(column_45,',','.') as FLOAT64 ) paid_price,
cast( replace(column_46,',','.') as FLOAT64 ) Advanced_Sales_Fee,
0.0 Delivery_Fee,
0.0 insurance_fee,
0.00 Flexible_Fee,
0.0 system_fee,
0.0 other_fee,
FROM  eci )



select 
 _file,
 _loaded_at, 
 _last_update, 
 'eci-es-_unk' as customer_id,
  source_code,
   concat(order_number, theatre_area, theatre_row, theatre_seat) as barcode,
  - 1 as client_id,
  - 1 as subclient_id,
  ifnull(affiliate,'_n/a') as subclient,
  - 1 as customer_code,
  order_number as main_order_number,
  - 1 as sub_order_number,
  timestamp( concat(booking_date, ' ', booking_time)) booking_timestamp,
  booking_date,
  booking_time,
  ifnull( booking_date ,'1900-01-01') reservation_date,
  cancellation_date cancellation_date,
  if( cancellation_status=0,0,1 ) cancellation_status,
  if( cancellation_status=0,'sale','cancellation' ) transaction_type,
  performance_date,
  performance_time,
  timestamp( concat (performance_date, ' ', performance_time))performance_date_time,
  ifnull( trim(production_or_show) ,'_n/a') as source_production,
  cast(null as string) as source_location,
  ifnull(trim(theatre_area), '_n/a') as source_seat,
  ifnull(trim( cast(theatre_row as string)), '_n/a') as seat_row,
  ifnull(trim( cast(theatre_seat as string)) ,  '_n/a') as seat_number,
  trim(price_category) as source_price_category_id,
  trim(price_category) as source_price_category_name,
  ifnull(trim(discount),  'no discount') as source_price_type_id,
  ifnull(trim(discount),  'no discount') as source_price_type_name,
  '_n/a' as source_price_type_amount,
  ifnull(trim(discount),  'no discount') as source_promotion_id,
  ifnull(trim(discount),  'no discount') as source_promotion_name,
  '_n/a' as source_promotion_amount,
  '_n/a' as source_promotion_group,
  '_n/a' as source_other_promotion_id,
  '_n/a' as source_other_promotion_name,
  '_n/a' as source_other_promotion_amount,
  '_n/a' as source_other_promotion_group,
  0.00  as producer_fee,
  0.00 as channel_fee,
  0.00  as channel_fee2,
  ifnull(delivery_fee,    0.00) as delivery_fee,
  ifnull(advanced_sales_fee,      0.00)  as advanced_sales_fee,
  ifnull(flexible_fee,      0.00) as flexible_fee,
  ifnull(system_fee,   0.00)  as system_fee,
  ifnull(insurance_fee,  0.00)  as insurance_fee,
  ifnull(other_fee,      0.00) other_ticket_fees,
  0 as ticket_fee1,
  ifnull(channel, '_n/a') as source_distribution_channel,
  '_n/a' as source_distribution_point_id,
  ifnull(trim(affiliate), '_n/a') as source_distribution_point,
  '_n/a' as source_referer,
   - 1 as web_order_number,
  'ES' as country_code,
  '_n/a' as venue_provincia,
  '_n/a' as venue_city,
  '_n/a' as source_campaign_code,
  -1 etl_file_upload_id,
  _file as file_id,
  -1 as end_price,
  ifnull(ticket_price,  0) as ticket_price_old,
  ifnull(paid_price,    0) as paid_price_old,
  ifnull(customer_price,  0) as customer_price_old,
  -1 as net_price_old,
  if (ticket_price = 0 , 'invitation'  ,  '_n/a'  ) as free_ticket_reason,
  ifnull(paid_price, 0) as paid_price,
  0 inside_commissions,
  ifnull(advanced_sales_fee, 0.00) as outside_commissions,
  ifnull(customer_price,  0) as customer_facevalue,
  0 as inside_commissions_resellers,
  ifnull(ticket_price,  0) as ticket_price,
  0 as deductions,
  0 as gbor_net,
  0 as nbor,
  -1 as sourcesubclientid,
  '_n/a' as source_promotion_code,
  '_n/a' as source_distribution_channel_name,
  '_n/a' as source_sales_partner,
  '_n/a' as source_sales_partner_class_id,
  '_n/a' as source_sales_partner_class,
  '_n/a' as source_agency_id,
  '_n/a' as source_device_type,
  '_n/a' as source_package_id

 from eci_data

