
version: 2
 
models:
  - name: article_types
    description: tables contains article types information 
    columns:
      - name: article_type_code
        description: article types code
        test :
          - not_null
          - unique
      - name: article_type_name
        description: article type name
      - name : last_update
        description: source file last update 

  - name: countries
    description: tables contains country information 
    columns:
      - name: country_code
        description: country code
        tests :
          - not_null
          - unique
      - name: country_name
        description: country name
      - name: currency_code
        description: country  currancy code
      - name: ticket_price_adjustment_factor
        description: ticket price adjustment factor
      - name: vat
        description: country vat
      - name: vat_high
        description: country vat high
      - name : last_update
        description: source file last update 
            
  - name: distributions
    description: table defining a logic that sets diverse criteria defining a distribution type, partner and other details to each ticket, using data that is contained in the source ticket data 
    columns:
      - name: country_code
        description: country code
      - name: distribution_id
        description: unique identifier for distribution
        tests :
          - not_null
          - unique
      - name: distribution_channel_code
        description: selection from table distribution_channel
      - name: distribution_channel_name
        description: option to name a logic/describe it
      - name: local_sales_channel_1
        description: selection from two channel types predefined by the group
      - name: local_sales_channel_2
        description: selection from several channel types predefined by the group
      - name: local_sales_channel_3
        description: selection from several channel types predefined by the group
      - name: distribution_point
        description: two types of use 1-more detailed description of a dedicated distribution owner or 2-description of a dedicated partner when distribution owner -level has been grouped
      - name: commission_percentage
        description: contained in commission model
      - name: kick_back_percentage
        description: contained in commission model
      - name: distribution_owner
        description: two types of use 1) dedicated name of sales partner/company or 2) grouping of smaller sales partners
      - name: distribution_logic
        description: logic combination of one or several source ticket data defining the selection of a ticket into this particular distribution
      - name: distribution_logic_priority
        description: definition of priority of this distribution logic for selection and labeling of a ticket"
      - name: channel_type_code
        description: selection from predefined list of codes/abbreviations
      - name: channel_type_name
        description: predefined full name for each channel type
      - name: is_distribution_owned_by_stage
        description: WE ARE NOT SURE AS WE DON'T FInD THIS IN MDS, should be a flag set to TRUE, when "Distribution Owner" = "Stage Entertainment"
      - name: discount_percentage
        description: "not used"
      - name: providing_customer_data_code
        description: true or false, selection from list defined in MDS table distribution_channel_providing_customer_data
      - name: providing_customer_data_name
        description:  description of providing_customer_data_code, from list defined in MDS table distribution_channel_providing_customer_data
      - name : last_update
        description: source file last update 

  - name: performances
    description: table contains data about performace 
    columns:
      - name: performance_id
        description: Unique ID of the Performance example DE - ALA - APO - 1 - 2022-09-01 19:30:00.0000000 - 19:30:00
        tests :
          - not_null
         
      - name: production_location_id
        description: id of  production location
      - name: season
        description: Information of the performance period (Year and Winter/Summer), bundle of perfomances of the setup document
      - name: setup
        description: Information if there is a standard Performance or if it is special in date, time, price or sales floor plan
      - name: sales_floor_plan
        description: 	Performance Sales Floor Plan	2	Number of the setting of floor regarding the price categories
      - name: performance_status
        description: Information about if the performance is shown at the shop and able to buy tickets (On Sale/Cancelled/Closed/In Planning)
      - name: performance_day_of_week
        description: Weekday of the performance
      - name: performance_time
        description: Time of the performance
      - name: show_code
        description: 	Performance Show Code	Thu3	Combination code of weekday and time 1<=15:30, 3>=19:00, 2=between
      - name: show
        description: Information about the perfomance time regarding afternoon or evening. Matinee<18:00, Soiree>=18:00
      - name: promotion_type
        description: Initial Setting for the promotion list
      - name: version
        description: Performance Version	1	Version of setup document
      - name: from_booking_date
        description: irst date able to buy tickets for the performance
      - name: performance_date
        description: Date of Performance
      - name: performance_time
        description: 	Information about performance time
      - name: is_buyout
        description: bolean shows Buyout means special conditions for the performance exclusive selling for special partner
      - name: performance_type
        description: Probably automatically filled by "Production Location Start Date (Preview/Premiere/Running Show)
      - name: performance_date_time
        description: Combination of date and time
      - name: performance_weekday_time
        description: Combination of weekday and time
      - name: production_location_show_number
        description: Count of performances since first performance incl. Previews
      - name: production_location_running_day
        description: Count of days since first performance incl. Previews without days that are without performance
      - name: production_location_capacity
        description: Seat capacity of the theatre
      - name: is_high_tax_rate
        description: "unknown"
      - name: is_active_performance
        description: "unknown"
      - name: dim_relocated_to_performance_id
        description: "unknown"
      - name: isrelocated
        description: "unknown"
      - name: performance_description
        description: Additional information about the performance about e. g. Covid batches, Preview, Derniere, Cast
      - name : last_update
        description: source file last update 

  - name: price_categories
    description: table contains price category data 
    columns:
      - name: price_category_id
        description: unique id for price category 
        tests :
          - not_null
          - unique
      - name: price_category_name
        description: our internal name of the price categories
      - name: sort_code
        description: ranking of price categories
      - name: price_category_group
        description: 3 level clustering of several price categories
      - name: country_code
        description: country code
      - name : last_update
        description: source file last update 

  - name: price_types
    description: Table contains  sales price type 
    columns:
      - name: price_type_id
        description: Combination of price type code and price type name
        tests :
          - not_null
          - unique
      - name: price_type_name
        description: "our internal name for a certain price type"
      - name: price_type_group
        description: "selection of predefined pt group of price typed for this particular pt"
      - name : last_update
        description: source file last update 

  - name: productions
    description: table contains data about production
    columns:
      - name: production_id
        description: unque id for production
        tests :
          - not_null
          - unique
      - name: country_code
        description: country short of the production
      - name: production_code
        description: code of production as ala
      - name: production_name
        description: Name of production as aladdain 
      - name: is_expired
        description: Information if the production is in selling at the moment or is expired
      - name: license_name
        description: Production License Name	Aladdin	License name
      - name: licensor
        description: Production Licensor	Disney Theatrical Productions Ltd.	Name of the licensor
      - name: license_type
        description: Production License Type	Musical	License type
      - name: production_id
        description: Combination of country code and production code  example 	DE - ALA
      - name: license_classification
        description: Production License Classification
      - name : last_update
        description: source file last update 

  - name: production_locations
    description: table conatins information about production location
    columns:
      - name: production_location_id
        description: unique id for production location
        tests :
          - not_null
          - unique
      - name: country_code
        description: Country short of the production location
      - name: country_name
        description: Country of the production location
      - name: dim_production_id
        description: Information about production
      - name: production_code
        description: Code of production example ALA
      - name: production_name
        description: Name of production Aladdin
      - name: dim_auditorium_id
        description: Information about auditorium
      - name: production_location_id
        description: Combination of country code, production code, theatre code and running number of production (location)
      - name: sales_start_date
        description: First date able to buy tickets for the production (location)
      - name: production_location_premiere_date
        description: Premiere of production (location)
      - name: production_location_start_date
        description: 	First Performance after the premiere (=first running show)
      - name: production_location_end_date
        description: Last performance (=derniere)
      - name: is_expired
        description: Information if the production is in selling at the moment or is expired
      - name: production_location_capacity
        description: Seat capacity of the theatre
      - name: production_location_description
        description: We do not use.
      - name: production_location_type
        description: Sit Down	Usually "Sit Down", in special cases "Tour" or "Event"
      - name: show_in_group_sales_reporting
        description: Some special data for a special reporting
      - name: show_in_group_salesreporting_name
        description: "unknown"
      - name : last_update
        description: source file last update 

  - name: theatres
    description: table conatins Information about theatre
    columns:
      - name: theatre_id
        description: unique id for theatre
        tests :
          - not_null
          - unique
      - name: country_code
        description: Country short of the theatre
      - name: theatre_code
        description: Code of the theatre
      - name: theatre_name
        description: Name of the theatre
      - name: address
        description: Address of the theatre
      - name: postcode
        description: Postal Code of the theatre
      - name: city_code
        description: City Code of the theatre
      - name: city
        description: City of the theatre
      - name: owner
        description:  who own the stage Usually Stage
      - name: max_capacity
        description: Max seat capacity of the theatre
      - name: is_theatre_owned_by_stage
        description: Information about if theatre is owned by stage
      - name : last_update
        description: source file last update 

  - name: cts_tickets
    description:  Table compained CTS data 
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - barcode 
            - transaction_type
            - booking_date

  - name: tickets_all_sources
    description:  Table compained all sales files table in on table 
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - source_code
            - barcode
            - booking_date
            - transaction_type

  - name: tickets_filtered
    description:  Table compained all sales files table in on table 
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - source_code
            - barcode
            - booking_date
            - transaction_type
 
  - name: tickets_mapped
    description:  Table containes tickets mapped 
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - barcode 
            - transaction_type
            - booking_date
            - source_code
            - country_code
        
  - name: tickets_mdb
    description:  Table containes tickets raw 
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
          - booking_date
          - ticket_id
          config:
            error_if: ">1000"
            warn_if: ">705"
            where : " not is_replaced_cancellation and replacement_type <> 'Original'"

  - name: tickets_union_mdb
    description:  Table containes tickets raw 
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
          - booking_timestamp
          - ticket_id
          config:
            where : "_source='BQ'"

  - name: tickets_mapped_distributions
    description:  Table containes tickets mapped 
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
          - booking_timestamp
          - ticket_id
          config:
            where : "_source='BQ'"
     
  - name: tickets
    description:  Table containes tickets mapped 
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
          - booking_timestamp
          - ticket_id
          config:
            where : "_source='BQ'"
        