
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'fivetran_dbt'
version: '1.2.0'
config-version: 2
require-dbt-version: [">=1.2.0", "<1.3.0"]

# This setting configures which "profile" dbt uses for this project.
profile: 'fivetran_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# dbt_project.yml

config-version: 2

seeds: 
  fivetran_dbt:
    +schema: seed_data
    description: dataset contains Seed data
    +persist_docs:
      relation: true
      columns: true

models:
  fivetran_dbt: # this matches the `name:`` config
    docs_background_color: 10C3C3
    +persist_docs:
      relation: true
      columns: true
    +materialized: table # this applies to all models in the current project
    ga:
      +schema: ga # this applies to all models in the `marts/ga/`` directory
      description: dataset contains google analystic data
    ga4:
      +schema: ga4 # this applies to all models in the `marts/ga/`` directory
      description: dataset contains google analystic 4 data
    marketing:
      +schema: marketing # this applies to all models in the `marts/marketing/`` directory
      description: dataset contains marketing  data
    marketing_offline:
      +schema: marketing # this applies to all models in the `marts/marketing_offline/`` directory
      description: dataset contains marketing  data
    crm:
      +schema: crm # this applies to all models in the `marts/crm/`` directory
      description: dataset contains crm  data
    sales:
      +schema: sales # this applies to all models in the `marts/sales/`` directory
      description: dataset contains sales and tickets  data
    sales_new:
      +schema: sales # this applies to all models in the `marts/sales/`` directory
      description: dataset contains sales and tickets  data
    staging:
      +schema: staging # this applies to all models in the `marts/staging/`` directory
      description: dataset contains staging  tickets  data

    admin:
      +schema: admin # this applies to all models in the `marts/admin/`` directory
      description: dataset contains admin table 
    dymatrix:
      +schema: dymatrix # this applies to all models in the `marts/admin/`` directory
      description: dataset contains dymatrix table 
    business:
      +schema: business # this applies to all models in the `marts/admin/`` directory
      description: dataset contains common table
    mreish:
      +schema: mreish # this applies to all models in the `marts/admin/`` directory
      description: dataset contains test table
    finance :
      +schema: finance # this applies to all models in the `marts/admin/`` directory
      description: dataset contains finance table

