
jobs:
# Give each job a unique name. The name will be displayed in the Fivetran dashboard once your jobs are imported.
# Job names must be unique.
 - name: Marketing_Models_Daily 
   targetName: prod # The name of the target that will be used when running the job. If it's not specified, the target will be named 'prod'.
   schedule: 0 10 * * * # Define when this job should run, using cron format. This example will run every day at 12:00pm (according to your warehouse timezone). For help with cron formatting, visit https://crontab.guru/.
   # Optional timeout that limits the maximum run time of the job. You can specify only hours, only minutes or both, for example "6h", "2h30m", "30m"
   # The value can be in range from 30 minutes to 24 hours.
   # If timeout is not specified, the job will be terminated after 24 hours.
   timeout: 2h30m
   steps:
     - name: run models # Give each step in your job a name. This will enable you to track the steps in the logs.
       command: dbt run --models marketing # Enter the dbt command that should run in this step. This example will run all your models. For a list of available commands visit https://docs.getdbt.com/reference/model-selection-syntax/.
     
     - name: test models
       command: dbt test --models marketing   # This example will run all your tests.

 - name: Check_Sources_Freshness_Daily 
   schedule: 10 1 * * * 
   steps:
     - name: run source freshness 
       command: dbt source freshness

 - name: Ga_Models_Daily 
   schedule: 13 10 * * * 
   steps:
     - name: run models # Give each step in your job a name. This will enable you to track the steps in the logs.
       command: dbt run --models ga # Enter the dbt command that should run in this step. This example will run all your models. For a list of available commands visit https://docs.getdbt.com/reference/model-selection-syntax/.
     
     - name: test models
       command: dbt test --models ga   # This example will run all your tests.

 - name: Sales_Models_Daily 
   schedule: 6 10 * * * 
   steps:
     - name: run models # Give each step in your job a name. This will enable you to track the steps in the logs.
       command: dbt run --models ga # Enter the dbt command that should run in this step. This example will run all your models. For a list of available commands visit https://docs.getdbt.com/reference/model-selection-syntax/.
     
     - name: test models
       command: dbt test --models ga   # This example will run all your tests.

 - name: dbt_version 
   schedule: 1 1 1 1 1 
   steps:
     - name: run version # Give each step in your job a name. This will enable you to track the steps in the logs.
       command: dbt --version # Enter the dbt command that should run in this step. This example will run all your models. For a list of available commands visit https://docs.getdbt.com/reference/model-selection-syntax/.
     
 
