fivetran_dbt:
  outputs:
    prod:
      dataset: admin
      job_execution_timeout_seconds: 600
      job_retries: 1
      keyfile:  ./fivetran-dbt-sa.json
      location: EU
      method: service-account
      priority: interactive
      database: stage-commercial
      threads: 10
      type: bigquery
    play:
      dataset: admin
      job_execution_timeout_seconds: 600
      job_retries: 1
      keyfile:  ./fivetran-dbt-sa.json   
      location: EU
      method: service-account
      priority: interactive
      database: stage-playground
      threads: 10
      type: bigquery
    cicd:
      dataset: admin
      job_execution_timeout_seconds: 600
      job_retries: 1
      keyfile:  ./fivetran-dbt-sa.json   
      location: EU
      method: service-account
      priority: interactive
      database: stage-cicd
      threads: 10
      type: bigquery
  target: play
