fivetran_dbt:
  outputs:
    prod:
      dataset: marketing
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ${{ secrets.DBT_COMMERCIAL_KEY }}  
      location: EU
      method: service-account
      priority: interactive
      project: stage-commercial
      threads: 10
      type: bigquery
    play:
      dataset: marketing
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ${{ secrets.DBT_COMMERCIAL_KEY }}    
      location: EU
      method: service-account
      priority: interactive
      project: stage-playground
      threads: 10
      type: bigquery
  target: play
