version: 2

sources:
  - name: 'gcp_logs'
    description:  all gcp ( bigQuery logs) sink 
    database: stage-landing
    tables:
      - name: cloudaudit_googleapis_com_data_access
        description: logs table
        loaded_at_field: timestamp(receiveTimestamp)
        freshness: 
          warn_after: {count: 1, period: day}
          error_after: {count: 2, period: day}
       



