
version: 2
 
models:
  - name: dim_customer
    description:  Table containes customer information shated with dymatric for crm system to read  
    columns:
      - name: country_code
        description: customer country code
      - name: golden_customer_id
        description: customer id
      - name: salutation
        description: customer inti
      - name: first_name
        description: customer first name
      - name: last_name
        description: customer last name
      - name: email
        description: customer email
      - name: company_name
        description: customer company name
      - name: birthday
        description: customer birthday
      - name: gender
        description: customer gender
      - name: customer_type
        description: customer type
      - name: mobile_number
        description: customer mobile number
      - name: customer_code
        description: customer code
      - name: city
        description: customer city
      - name: postcode
        description: customer postcode
      - name: phone_number
        description: customer phone number 
      - name: created_on
        description: timestamp when customer was created 
      - name: last_modified_on
        description: timestamp when customer was last modified