version: 2

sources:
  - name: 'ft_media_data'
    description:  marketing data gethered from media agency 
    database: stage-landing
    tags: ['marketing']     
    tables:
      - name: mind_share
        description: table conatins all mida share data
        loaded_at_field: _fivetran_synced
        freshness: 
          warn_after: {count: 2, period: day}
          error_after: {count: 50, period: day}
       
