
version: 2
 
models:

  - name: ga_data
    description: table contains ga data per sessiion - each row contains data or a full session https://support.google.com/analytics/answer/3437719?hl=en
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - full_visitor_id
            - visit_id
            - date
            - country
            
            
    columns:
      - name: date
        description: The date of the session
        tests:
          - not_null 

      - name: full_visitor_id
        description: The unique visitor ID

      - name: visit_id
        description: An identifier for this session. This is part of the value usually stored as the _utmb cookie. This is only unique to the user. For a completely unique ID, you should use a combination of fullVisitorId and visitId

      - name: country
        description: County of the GA
        tests:
          - not_null

      - name: visit_start_time
        description: Visit timestamp

      - name: traffic_source
        description: This section contains information about the Traffic Source from which the session originated
      - name: traffic_source.campaign
        description: The campaign value. Usually set by the utm_campaign URL parameter
      - name: traffic_source.medium
        description: The medium of the traffic source. Could be "organic", "cpc", "referral", or the value of the utm_medium URL parameter.
      - name: traffic_source.source
        description: The source of the traffic source. Could be the name of the search engine, the referring hostname, or a value of the utm_source URL parameter
      - name: traffic_source.ad_network_type
        description: Network Type. Takes one of the following values Google Search, Content, Search partners, Ad Exchange, Yahoo Japan Search, Yahoo Japan AFS, unknown

      - name: device
        description: This section contains information about the user devices
      - name: device.device_category
        description: The type of device (Mobile, Tablet, Desktop)
      - name: device.browser
        description: The browser used (e.g., "Chrome" or "Firefox")

      - name: geo_network
        description: This section contains information about the geography of the user
      - name: geo_network.geo_country
        description: The country from which sessions originated, based on IP address
      - name: geo_network.geo_city
        description: Users' city, derived from their IP addresses or Geographical IDs
      - name: geo_network.geo_region
        description: The region from which sessions originate, derived from IP addresses. In the U.S., a region is a state, such as New York

      - name: channel_grouping
        description: The Default Channel Group associated with an end user's session for this View

      - name: totals
        description: 	This section contains aggregate values across the session
      - name: totals.visits
        description: The number of sessions (for convenience). This value is 1 for sessions with interaction events. The value is null if there are no interaction events in the session
      - name: totals.hits
        description: Total number of hits within the session
      - name: totals.pageviews
        description: Total number of pageviews within the session
      - name: totals.time_on_site
        description: 	Total time of the session expressed in seconds
      - name: totals.bounces
        description: Total bounces (for convenience). For a bounced session, the value is 1, otherwise it is null
      - name: totals.transactions
        description: Total number of ecommerce transactions within the session
      - name: totals.total_transaction_revenue
        description: Total transaction revenue
      - name: totals.new_visits
        description: boolean show if the user is new
      - name: totals.session_quality_dim
        description: An estimate of how close a particular session was to transacting, ranging from 1 to 100, calculated for each session. A value closer to 1 indicates a low session quality, or far from transacting, while a value closer to 100 indicates a high session quality, or very close to transacting. A value of 0 indicates that Session Quality is not calculated for the selected time range
      - name: totals.unique_articles
        description: number of unique articale purchased in this sessios			
      - name: totals.total_articles
        description: total number or articales parchased on this session 

      - name: hits
        description: record contains data bout visit   hits
      - name: hits.hits_type
        description: The type of hit One of  PAGE, TRANSACTION, ITEM, EVENT, SOCIAL, APPVIEW, EXCEPTION. Timing hits are considered an event type in the Analytics backend. When you query time-related fields (e.g., hits.latencyTracking.pageLoadTime), choose hits.type as Event if you want to use hit.type in your queries
      - name: hits.event_action
        description: The event action
      - name: hits.event_category
        description: 	The event category
      - name: hits.event_label
        description: The event label
      - name: hits.transaction_id
        description: The transaction ID of the ecommerce transaction
      - name: hits.revenue
        description: ER	Total revenue from the item - Value\10^6
      - name: hits.affiliation
        description: The affiliate information passed to the ecommerce tracking code
      - name: hits.source_property_tracking_id
        description: Source property tracking ID of roll-up properties. This is valid for only roll-up properties
      - name: hits.hits_timestampe
        description: Timestame of hit
      - name: hits.time
        description: secands after first hit
      - name: hits.hit_number
        description: The sequenced hit number. For the first hit of each session, this is set to 1
      - name: hits.is_interaction
        description: ""
      - name: hits.page_path
        description: The URL path of the page
      - name: hits.hostname
        description: The hostname of the URL
      - name: hits.page_title
        description: 	The page title
      - name: hits.page_group
        description: page group of session
      - name: hits.is_show
        description: boolean show if the page group is related to a show or not    
      - name: hits.page_group_desc
        description: desc of the page group - if musical or informational page ot checkout 
      - name: hits.page_group_type
        description: page type ( infomational or check out or show etc )
      - name: hits.screen_name
        description: The name of the screen
      
      - name: optin
        description: boolean show if the session has an optin event 
      - name: newsletter
        description: boolean show if the session has an newsletter event
      - name: ecommerce
        description: boolean show if the session has an ecommerce event
      
      - name:   experiment
        description: repeted records contains experiments used in the session 
      - name:   experiment.experiment_id
        description: contains latest ( not null) id for ab test base on session 
      - name:   experiment.experiment_variant
        description: The variation or combination of variations present in a hit for an experiment 
      
      - name:   product
        description: record contains productions (articales) which were bought duing the session
      - name:   product.transaction_id
        description: record contains productions (articales) which were bought duing the session 
      - name:   product.product_name
        description: Product Name 
      - name:   product.product_revenue
        description: The revenue of the product in local currency, expressed as the value passed to Analyticsn 
      - name:   product.product_price
        description: The price of the product, expressed as the value passed to Analytics
      - name:   product.product_quantity
        description: The quantity of the product purchased

      - name:   landing_page
        description: contains latest ( not null) id for ab test base on session    
      - name: landing_page.landing_page_path
        description: 	landing page path  
      - name: landing_page.landing_page_group
        description: langing page group of session
      - name: landing_page.landing_page_group_desc
        description: landing page desc of the page group - if musical or informational page ot checkout      
      - name: landing_page.landing_page_group_type
        description: landing page type ( infomational or check out or show etc ) 
     


  - name: ga_daily_summery
    description: ga data sessions aggragded per on day - country 
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date
            - country

    columns:
      - name: date
        description: The date of the session
      - name: country
        description: country of the the first hit in the session bases on hostname 
      - name: visitors
        description: count of the visits / sessions on that date 
      - name: unique_visitors
        description: count of unique vistors on that date
      - name: new_vistor
        description: count of new visitor on that date
      - name: bounces
        description: count of bounces session on that date
      - name: pageviews
        description: count of the pages views  on that date
      - name: transactions
        description: count of transaction based on GA data 
      - name: total_transaction_revenue
        description: sum of transaction revenue bases on GA data 
      - name: time_on_site
        description: sum on time on site that day
      - name: converstion
        description: count of session with financial transaction on count of all sessions
      - name: optin
        description: count of sesstions with optin events 
      - name: newsletter
        description: count of sesstions with newsletter events 
      - name: ecommerce
        description: count of sesstions with ecommerce events 

 
  - name: ga_daily_page_group
    description: ga data aggragded on counrty and page group level 
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date
            - country
            - page_group
      - dbt_utils.expression_is_true:
          expression: page_group = 'Error'  
          config:
              severity: error
              error_if: ">100000"
              warn_if: ">80000"
      - dbt_utils.expression_is_true:
          expression: page_group = 'Others'  
          config:
              severity: error
              error_if: ">150000"
              warn_if: ">100000"

    columns:
      - name: date
        description: The date of the session
      - name: country
        description: country of ga view 
      - name: page_group
        description: hit page group based on page path - incase of a show its Production Location Id
      - name: group_desc 
        description: page group desception based on manual entry by seed 
      - name: production_name 
        description: if the page is a show - production name  
      - name: is_show
        description: is the page a show page 
      - name: visitors
        description: count of the visit on tha page 
      - name: unique_visitors
        description: count of unique vistors on the page 
      - name: new_vistor
        description: count of new visitor on the page
      - name: impressions
        description: count of the hits on the page 


  - name: ga_daily_transactions
    description: table contains ga transactions linked to MDB data 
    columns:
      - name: date
        description: The date of the session when transaction happened  
      - name: country
        description: country of ga view 
      - name: full_visitor_id
        description: The unique visitor ID
      - name: hostname
        description:  The hostname of the URL
      - name: transaction_id
        description: transaction id
        tests:
          - unique
          - not_null
      - name: revenue
        description: revenue of the transaction 
      - name: affiliation
        description:  The affiliate information passed to the ecommerce tracking code
  
  - name: web_sales
    description: sales ticket where distribution_point in ('stage-entertainment.nl','stage-entertainment.fr' ,'musicals.de' ,'ElReyLeon.es','Tina.es') and booked after 2021

    columns:
      - name: country_code
        description: ticket country code

      - name: country
        description: ticket country

      - name: booking_date
        description: ticket booking date 

      - name: week
        description: ticket booking date week

      - name: production_location_id
        description: production location id for the ticket

      - name: production_name
        description: production name for the ticket

      - name: article_type_code
        description: ticket artical type

      - name: price_type_name
        description: price type name 

      - name: fact_ticket_sales_id
        description: ticket id

      - name: web_order_number
        description: ticket web order number AKA transation id in GA

      - name: cancellation_status
        description: boolean if the ticket cancelled

      - name: article_count
        description: artical count 

      - name: euro_paid_price
        description: ticket price