
version: 2
 
models:

  - name: ga_data
    description: table contains ga data per sessiion - each row contains data or a full session 
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - full_visitor_id
            - visit_id
            
            
    columns:
      - name: date
        description: The date of the session
        tests:
          - not_null 

      - name: full_visitor_id
        description: The unique visitor ID

      - name: visit_id
        description: An identifier for this session. This is part of the value usually stored as the _utmb cookie. This is only unique to the user. For a completely unique ID, you should use a combination of fullVisitorId and visitId

      - name: country
        description: County of the GA
        tests:
          - not_null

      - name: visit_start_time
        description: Visit timestamp

      - name: traffic_source
        description: This section contains information about the Traffic Source from which the session originated

      - name: campaign
        description: The campaign value. Usually set by the utm_campaign URL parameter

      - name: medium
        description: The medium of the traffic source. Could be "organic", "cpc", "referral", or the value of the utm_medium URL parameter.

      - name: source
        description: The source of the traffic source. Could be the name of the search engine, the referring hostname, or a value of the utm_source URL parameter
      
      - name: ad_network_type
        description: Network Type. Takes one of the following values Google Search, Content, Search partners, Ad Exchange, Yahoo Japan Search, Yahoo Japan AFS, unknown

      - name: device
        description: This section contains information about the user devices

      - name: device_category
        description: The type of device (Mobile, Tablet, Desktop)

      - name: browser
        description: The browser used (e.g., "Chrome" or "Firefox")

      - name: geo_network
        description: This section contains information about the geography of the user

      - name: geo_country
        description: The country from which sessions originated, based on IP address

      - name: geo_city
        description: Users' city, derived from their IP addresses or Geographical IDs

      - name: geo_region
        description: The region from which sessions originate, derived from IP addresses. In the U.S., a region is a state, such as New York

      - name: channel_grouping
        description: The Default Channel Group associated with an end user's session for this View

      - name: totals
        description: 	This section contains aggregate values across the session

      - name: visits
        description: The number of sessions (for convenience). This value is 1 for sessions with interaction events. The value is null if there are no interaction events in the session

      - name: hits
        description: Total number of hits within the session

      - name: pageviews
        description: Total number of pageviews within the session

      - name: time_on_site
        description: 	Total time of the session expressed in seconds

      - name: bounces
        description: Total bounces (for convenience). For a bounced session, the value is 1, otherwise it is null

      - name: transactions
        description: Total number of ecommerce transactions within the session

      - name: total_transaction_revenue
        description: Total transaction revenue

      - name: new_visits
        description: boolean show if the user is new

      - name: session_quality_dim
        description: An estimate of how close a particular session was to transacting, ranging from 1 to 100, calculated for each session. A value closer to 1 indicates a low session quality, or far from transacting, while a value closer to 100 indicates a high session quality, or very close to transacting. A value of 0 indicates that Session Quality is not calculated for the selected time range

      - name: hits
        description: record contains data bout visit   hits

      - name: hits_type
        description: The type of hit One of  PAGE, TRANSACTION, ITEM, EVENT, SOCIAL, APPVIEW, EXCEPTION. Timing hits are considered an event type in the Analytics backend. When you query time-related fields (e.g., hits.latencyTracking.pageLoadTime), choose hits.type as Event if you want to use hit.type in your queries

      - name: event_action
        description: The event action

      - name: event_category
        description: 	The event category

      - name: event_label
        description: The event label

      - name: web_order_id
        description: The transaction ID of the ecommerce transaction

      - name: revenue
        description: ER	Total revenue from the item - Value\10^6

      - name: affiliation
        description: The affiliate information passed to the ecommerce tracking code
  
      - name: source_property_tracking_id
        description: Source property tracking ID of roll-up properties. This is valid for only roll-up properties

      - name: hits_timestampe
        description: Timestame of hit

      - name: time
        description: secands after first hit

      - name: hit_number
        description: The sequenced hit number. For the first hit of each session, this is set to 1

      - name: is_interaction
        description: ""

      - name: page_path
        description: The URL path of the page

      - name: hostname
        description: The hostname of the URL

      - name: page_title
        description: 	The page title
      
      - name: page_group
        description: page group of session

      - name: is_show
        description: boolean show if the page group is related to a show or not 
     
      - name: group_desc
        description: desc of the page group - if musical or informational page ot checkout 

      - name: screen_name
        description: The name of the screen
      - name: optin
        description: boolean show if the session has an optin event 
      - name: newsletter
        description: boolean show if the session has an newsletter event
      - name: ecommerce
        description: boolean show if the session has an ecommerce event
      
      - name:   experiment_id
        description: contains latest ( not null) id for ab test base on session 


  - name: ga_daily_sessions
    description: ga data sessions aggragded per on day - country 
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date
            - country

    columns:
      - name: date
        description: The date of the session
      - name: country
        description: country of the the first hit in the session bases on hostname 
      - name: visitors
        description: count of the visits / sessions on that date 
      - name: unique_visitors
        description: count of unique vistors on that date
      - name: new_vistor
        description: count of new visitor on that date
      - name: bounces
        description: count of bounces session on that date
      - name: pageviews
        description: count of the pages views  on that date
      - name: transactions
        description: count of transaction based on GA data 
      - name: total_transaction_revenue
        description: sum of transaction revenue bases on GA data 
      - name: time_on_site
        description: sum on time on site that day
      - name: converstion
        description: count of session with financial transaction on count of all sessions
      - name: optin
        description: count of sesstions with optin events 
      - name: newsletter
        description: count of sesstions with newsletter events 
      - name: ecommerce
        description: count of sesstions with ecommerce events 

 
  - name: ga_daily_page_group
    description: ga data aggragded on counrty and page group level 
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date
            - country
            - page_group
      - dbt_utils.expression_is_true:
          expression: page_group = 'Error'  
          config:
              severity: error
              error_if: ">10000"
              warn_if: ">8000"
      - dbt_utils.expression_is_true:
          expression: page_group = 'Others'  
          config:
              severity: error
              error_if: ">15000"
              warn_if: ">10000"

    columns:
      - name: date
        description: The date of the session
      - name: country
        description: country of ga view 
      - name: page_group
        description: hit page group based on page path - incase of a show its Production Location Id
      - name: group_desc 
        description: page group desception based on manual entry by seed 
      - name: production_name 
        description: if the page is a show - production name  
      - name: is_show
        description: is the page a show page 
      - name: visitors
        description: count of the visit on tha page 
      - name: unique_visitors
        description: count of unique vistors on the page 
      - name: new_vistor
        description: count of new visitor on the page
      - name: impressions
        description: count of the hits on the page 


  - name: ga_daily_transactions
    description: table contains ga transactions linked to MDB data 
    columns:
      - name: date
        description: The date of the session when transaction happened  
      - name: country
        description: country of ga view 
      - name: full_visitor_id
        description: The unique visitor ID
      - name: hostname
        description:  The hostname of the URL
      - name: web_order_id
        description: transaction id
        tests:
          - unique
          - not_null
      - name: revenue
        description: revenue of the transaction 
      - name: affiliation
        description:  The affiliate information passed to the ecommerce tracking code
      - name: ticket_sales
        description: linked data from MDB - Linked Transaction id = order_web_id 
