version: 2

sources:
  - name: 'ft_mdb_dbo'
    description:  MDB database 
    database: stage-landing
    tables:
      - name: factticketsales
        description:  Historical Sales Data 


  - name: 'ft_mdb7_se'
    description:  MDB database 
    database: stage-landing
    tables:
      - name: fact_ticket_sales_bq
        description:  Each row within a table is information about ticket /*timestamp(PARSE_DATE("%Y%m%d", cast(DimBookingDateId as string )) )*/
        loaded_at_field: _fivetran_synced  
        freshness: 
          warn_after: {count: 1, period: day}
          error_after: {count: 1, period: day}  
      

  - name: 'ft_mdb7_dbo'
    description:  export data from 3rd party for hotel and ticket in spain 
    database: stage-landing
    tables:
      - name: dimgoldencustomer
        description: Customer Data copied from MDB  
        loaded_at_field: _fivetran_synced
        freshness: 
          warn_after: {count: 1, period: day}
          error_after: {count: 1, period: day}  
      - name: dimperformance
        description: Perfomance Data copied from MDB 
      - name: dimdistribution
        description: Distribution Data copied from MDB 
      - name:  dimproduction
        description: Production Data copied from MDB 
      - name:  dimproductionlocation
        description: Production Location Data copied from MDB 
      - name:  dimpricecategory
        description: Price category Location Data copied from MDB 
      - name:  dimpricetype
        description: Price type  Data copied from MDB 
      - name:  dimcustomer
        description: customer   Data copied from MDB 

          
            
 