version: 2

sources:
  - name: 'ft_mdb2_se'
    description:  MDB database 
    database: stage-landing
    tables:
      - name: fact_ticket_sales_bq
        description:  Each row within a table is information about ticket
        loaded_at_field: timestamp(PARSE_DATE("%Y%m%d", cast(DimBookingDateId as string )) )
        freshness: 
          warn_after: {count: 2, period: day}
          error_after: {count: 7, period: day}  

  - name: 'ft_mdb2_dbo'
    description:  export data from 3rd party for hotel and ticket in spain 
    database: stage-landing
    tables:
      - name: dimgoldencustomer
        description: Customer Data copied from MDB  
        loaded_at_field: _fivetran_synced
        freshness: 
          warn_after: {count: 2, period: day}
          error_after: {count: 7, period: day}  
           
            
