version: 2


sources:
  - name: 'analytics_272653220'
    description:  Google Analytic 4 row data, linked with DE - Germeny 
    database: stage-landing
    tags: ['ga4'] 
    tables:
      - name: events_2023*
        description:  Each row within a table corresponds to a event in GA4
        loaded_at_field: timestamp(PARSE_DATE("%Y%m%d",event_date))
        freshness: 
          warn_after: {count: 200, period: day}
          error_after: {count: 305, period: day}  
 
  - name: 'analytics_272654930'
    description:  Google Analytic 4 row data, linked with ES - Spain 
    database: stage-landing
    tags: ['ga4'] 
    tables:
      - name: events_2023*
        description:  Each row within a table corresponds to a event in GA4
        loaded_at_field: timestamp(PARSE_DATE("%Y%m%d",event_date))
        freshness: 
          warn_after: {count: 200, period: day}
          error_after: {count: 305, period: day}  

  - name: 'analytics_272676813'
    description:  Google Analytic 4 row data, linked with NL - Neherlands 
    database: stage-landing
    tags: ['ga4'] 
    tables:
      - name: events_2023*
        description:  Each row within a table corresponds to a event in GA4
        loaded_at_field: timestamp(PARSE_DATE("%Y%m%d",event_date))
        freshness: 
          warn_after: {count: 200, period: day}
          error_after: {count: 305, period: day}  
           
  - name: 'analytics_272685101'
    description:  Google Analytic 4 row data, linked with FR - France 
    database: stage-landing
    tags: ['ga4'] 
    tables:
      - name: events_2023*
        description:  Each row within a table corresponds to a event in GA4
        loaded_at_field: timestamp(PARSE_DATE("%Y%m%d",event_date))
        freshness: 
          warn_after: {count: 200, period: day}
          error_after: {count: 305, period: day}  
  