
version: 2

seeds:
      - name: ga_hostnames
        description: hostname for our ga data
        columns:
          - name: hostname
            description: hostname wher ga data comes from
            test:
              - unique
          - name: country
            description: contry owned hostname 
          - name: internal
            description: boolean show if the host name is internal website or external 
    
      - name: ga_page_groups
        description: ga page groups 
        columns:
          - name: page_group
            description: hostname wher ga data comes from
          - name: is_show
            description: boolean show if the page group is related to a show or not 
          - name: group_desc
            description: desc of the page group - if musical or informational page ot checkout  
    
      - name: ga_event_types
        description: ga event types bases on our internal defintion  
        columns:
          - name: event_category
            description: 	The event category
          - name: event_types
            description: ga event types - as optin , ecommerce or newsletter 

      - name: dc_media_budget 
        description: digital commerce media budget  
        columns:
          - name: month
            description: 	month as yyyy-mm
          - name: month_date
            description: month as first day of the month trunctae
          - name: digital_commerce_media_budget
            description: media_ udget

      - name: sales_age
        description: ""
        columns:
          - name: dim_age_id
            description: ""
          - name: age_code
            description: ""
          - name: age_name
            description: ""
          - name: age_decenia_bin_code
            description: ""
          - name: age_decenia_bin_name
            description: ""
          - name: age_bin_a
            description: ""
          - name: age_bin_a_id
            description: ""
          - name: age_bin_b
            description: ""
          - name: age_bin_b_id
            description: ""
          - name: age_bin_d_id
            description: ""
          - name: age_bin_d
            description: ""
          - name: age_bin_c
            description: ""
          - name: age_bin_c_id
            description: ""

      - name: sales_article_type
        description: ""
        columns:
          - name: dim_article_type_id
            description: ""
          - name: article_type_code
            description: ""
          - name: article_type_name
            description: ""

      - name: sales_country
        description: ""
        columns:
          - name: dim_country_id
            description: ""
          - name: country_code
            description: ""
          - name: country_name
            description: ""
          - name: currency_code
            description: ""
          - name: ticket_price_adjustment_factor
            description: ""

      - name: sales_distribution
        description: ""
        columns:
          - name: dim_distribution_id
            description: ""
          - name: distribution_id
            description: ""
          - name: dim_country_id
            description: ""
          - name: dim_source_id
            description: ""
          - name: distribution_channel_code
            description: ""
          - name: distribution_channel_name
            description: ""
          - name: local_sales_channel_1
            description: ""
          - name: local_sales_channel_2
            description: ""
          - name: distribution_point
            description: ""
          - name: commission_percentage
            description: ""
          - name: kick_back_percentage
            description: ""
          - name: distribution_owner
            description: ""
          - name: distribution_logic
            description: ""
          - name: distribution_logic_priority
            description: ""
          - name: channel_type_code
            description: ""
          - name: channel_type_name
            description: ""
          - name: is_distribution_owned_by_stage
            description: ""
          - name: discount_percentage
            description: ""
          - name: providing_customer_data_code
            description: ""
          - name: providing_customer_data_name
            description: ""

      - name: sales_performance
        description: ""
        columns:
          - name: dim_performance_id
            description: ""
          - name: dim_performance_date_id
            description: ""
          - name: dim_production_location_id
            description: ""
          - name: performance_id
            description: ""
          - name: season
            description: ""
          - name: setup
            description: ""
          - name: sales_floor_plan
            description: ""
          - name: performance_status
            description: ""
          - name: performance_day_of_week
            description: ""
          - name: performance_time
            description: ""
          - name: show_code
            description: ""
          - name: show
            description: ""
          - name: promotion_type
            description: ""
          - name: version
            description: ""
          - name: from_booking_date
            description: ""
          - name: performance_date
            description: ""
          - name: dim_performance_time_id
            description: ""
          - name: is_buyout
            description: ""
          - name: performance_type
            description: ""
          - name: performance_date_time
            description: ""
          - name: performance_weekday_time
            description: ""
          - name: production_location_show_number
            description: ""
          - name: production_location_running_day
            description: ""
          - name: production_location_capacity
            description: ""
          - name: is_high_tax_rate
            description: ""
          - name: is_active_performance
            description: ""
          - name: dim_relocated_to_performance_id
            description: ""
          - name: isrelocated
            description: ""
          - name: dim_relocated_to_performance_date_id
            description: ""
          - name: dim_relocated_to_performance_time_id
            description: ""
          - name: performance_description
            description: ""

      - name: sales_price_category
        description: ""
        columns:
          - name: dim_price_category_id
            description: ""
          - name: price_category_id
            description: ""
          - name: price_category_name
            description: ""
          - name: sort_code
            description: ""
          - name: price_category_group
            description: ""
          - name: dim_production_location_id
            description: ""

      - name: sales_price_type
        description: ""
        columns:
          - name: dim_price_type_id
            description: ""
          - name: price_type_id
            description: ""
          - name: price_type_name
            description: ""
          - name: price_type_group
            description: ""

      - name: sales_production
        description: ""
        columns:
          - name: dim_production_id
            description: ""
          - name: country_code
            description: ""
          - name: country_name
            description: ""
          - name: production_code
            description: ""
          - name: production_name
            description: ""
          - name: is_expired
            description: ""
          - name: license_name
            description: ""
          - name: licensor
            description: ""
          - name: license_type
            description: ""
          - name: production_id
            description: ""
          - name: license_classification
            description: ""

      - name: sales_production_location
        description: ""
        columns:
          - name: dim_production_location_id
            description: ""
          - name: country_code
            description: ""
          - name: country_name
            description: ""
          - name: dim_production_id
            description: ""
          - name: production_code
            description: ""
          - name: production_name
            description: ""
          - name: dim_auditorium_id
            description: ""
          - name: production_location_id
            description: ""
          - name: sales_start_date
            description: ""
          - name: production_location_premiere_date
            description: ""
          - name: production_location_start_date
            description: ""
          - name: production_location_end_date
            description: ""
          - name: is_expired
            description: ""
          - name: production_location_capacity
            description: ""
          - name: production_location_description
            description: ""
          - name: production_location_type
            description: ""
          - name: show_in_group_sales_reporting
            description: ""
          - name: show_in_group_salesreporting_name
            description: ""

      - name: sales_source
        description: ""
        columns:
          - name: dim_source_id
            description: ""
          - name: source_code
            description: ""
          - name: source_name
            description: ""
          - name: source_group
            description: ""
          - name: is_active_source
            description: ""
          - name: is_active_ticket_source
            description: ""
          - name: is_active_digital_traffic_source
            description: ""

      - name: sales_theatre
        description: ""
        columns:
          - name: dim_theatre_id
            description: ""
          - name: country_code
            description: ""
          - name: country_name
            description: ""
          - name: theatre_id
            description: ""
          - name: theatre_code
            description: ""
          - name: theatre_name
            description: ""
          - name: address
            description: ""
          - name: postcode
            description: ""
          - name: city_code
            description: ""
          - name: city
            description: ""
          - name: owner
            description: ""
          - name: max_capacity
            description: ""
          - name: is_theatre_owned_by_stage
            description: ""

