
version: 2

seeds:
      - name: ga_hostnames
        description: hostname for our ga data
        columns:
          - name: hostname
            description: hostname wher ga data comes from
            test:
              - unique
          - name: country
            description: contry owned hostname 
          - name: internal
            description: boolean show if the host name is internal website or external 
    
      - name: ga_page_groups
        description: ga page groups 
        columns:
          - name: page_group
            description: hostname wher ga data comes from
          - name: is_show
            description: boolean show if the page group is related to a show or not 
          - name: group_desc
            description: desc of the page group - if musical or informational page ot checkout  
    
      - name: ga_event_types
        description: ga event types bases on our internal defintion  
        columns:
          - name: event_category
            description: 	The event category
          - name: event_types
            description: ga event types - as optin , ecommerce or newsletter 

      - name: dc_media_budget 
        description: digital commerce media budget  
        columns:
          - name: month
            description: 	month as yyyy-mm
          - name: month_date
            description: month as first day of the month trunctae
          - name: digital_commerce_media_budget
            description: media_ udget

      - name: sales_age
        description: ""
        columns:
          - name: dim_age_id
            description: ""
          - name: age_code
            description: ""
          - name: age_name
            description: ""
          - name: age_decenia_bin_code
            description: ""
          - name: age_decenia_bin_name
            description: ""
          - name: age_bin_a
            description: ""
          - name: age_bin_a_id
            description: ""
          - name: age_bin_b
            description: ""
          - name: age_bin_b_id
            description: ""
          - name: age_bin_d_id
            description: ""
          - name: age_bin_d
            description: ""
          - name: age_bin_c
            description: ""
          - name: age_bin_c_id
            description: ""

