
version: 2

seeds:
  - name: ga_hostnames
    description: hostname for our ga data
    columns:
      - name: hostname
        description: hostname wher ga data comes from
      - name: country
        description: contry owned hostname 
      - name: internal
        description: boolean show if the host name is internal website or external 

  - name: ga_page_groups
    description: ga page groups 
    columns:
      - name: page_group
        description: hostname wher ga data comes from
      - name: is_show
        description: boolean show if the page group is related to a show or not 
      - name: group_desc
        description: desc of the page group - if musical or informational page ot checkout  