
version: 2

seeds:
  - name: ga_hostnames
    description: hostname for our ga data
    columns:
      - name: hostname
        description: hostname wher ga data comes from
        test:
          - unique
      - name: country
        description: contry owned hostname 
      - name: internal
        description: boolean show if the host name is internal website or external 

  - name: ga_page_groups
    description: ga page groups 
    columns:
      - name: page_group
        description: hostname wher ga data comes from
      - name: is_show
        description: boolean show if the page group is related to a show or not 
      - name: group_desc
        description: desc of the page group - if musical or informational page ot checkout  

  - name: ga_event_types
    description: ga event types bases on our internal defintion  
    columns:
      - name: event_category
        description: 	The event category
      - name: event_types
        description: ga event types - as optin , ecommerce or newsletter 
