
version: 2
 
models:

  - name: stage_ventas_packs
    description:  Table containes data of hotel and tickets for spain by the revenue labs 
    columns:
      - name: _line
        description:  "metaData for the line on the csv file"
      - name:  fecha_compra
        description:  "date of purchase" 
      - name:  musical
        description:  "show"
      - name:  fecha_check_in
        description:  "check in date"
      - name:  fecha_check_out
        description:  "check out date"
      - name:  numero_de_entradas
        description:  "number of tickets"
      - name: fecha_sesion
        description:  "performance date"
      - name:  sesion
        description: "performance"
      - name:  hotel
        description:  "hotel"
      - name:  referencia
        description: "reference" 
      - name:  importe_total
        description:  "total value" 
      - name:  importe_entradas
        description:  "tickets value" 
      - name:  importe_hotel
        description: "hotel value"
      - name:  comision_a_stage_iva_incluido
        description:  "commission for Stage – VAT included"
      - name:  hotel_cancelado
        description:  "hotel cancelled"
      - name:  factura
        description:   "bill"
      - name:  pagado
        description:   "paid"


  - name: segmentation_panel
    description: "Segmentation survey questions and answers at responses level"
    columns:
      - name: user_id
        description: "User response identifier for the survey"
      - name: country
        description: "Country of the survey"
      - name: survey_i
        description: "Survey identifier"
      - name: sample
        description: "Survey sample number"
      - name: question
        description: "Question code"
      - name: answer
        description: "Survey response"

  - name: segmentation_crm
    description: "Segmentation survey questions and answers at responses level"
    columns:
      - name: user_id
        description: "User response identifier for the survey"
      - name: country
        description: "Country of the survey"
      - name: survey_i
        description: "Survey identifier"
      - name: question
        description: "Question code"
      - name: answer
        description: "Survey response"