version: 2

sources:
  - name: 'ft_therevenuelabs'
    description:  export data from 3rd party for hotel and ticket in spain 
    database: stage-landing
    tags: ['crm'] 
    tables:
      - name: stage_ventas_packs
        description: stage hotel and tickets data from 3rd party uploaded to cloud bucket
        loaded_at_field: _fivetran_synced
        freshness: 
          warn_after: {count: 2, period: day}

  - name: 'upload'
    description: data set for tables were created by uploading files 
    database: stage-landing
    tags: ['crm'] 
    tables:
      - name: segmentation_crm
        description: segmentation crm table
      - name: segmentation_panel
        description: segmentation panel table
        


          

       
