{% macro get_production_name(  page_path ) %}
   CASE
      WHEN ( LOWER(  {{ page_path }}) LIKE '%hamilton%') THEN 'Hamilton'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%mamma%') THEN 'Mamma-Mia'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%der%koenig%' 
				OR LOWER(  {{ page_path }}) LIKE '%der%köenig%' 
				OR LOWER(  {{ page_path }}) LIKE '%der%könig%' ) THEN 'The Lion King'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%eiskoenigin%'OR LOWER(  {{ page_path }}) LIKE '%eisköenigin%'
      	OR LOWER(  {{ page_path }}) LIKE '%eiskönigin%' ) THEN 'Frozen'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%wicked%') THEN 'Wicked'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%tina%'AND LOWER(  {{ page_path }}) LIKE '%hamburg%' ) THEN 'Tina-Hamburg'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%tina%' AND LOWER(  {{ page_path }}) LIKE '%stuttgart%' ) THEN 'Tina-Stuttgart'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%/tina%' ) THEN 'Tina'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%blue%') THEN 'Blue Man Group'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%kudamm%'
      	OR LOWER(  {{ page_path }}) LIKE "%ku\'damm%" ) THEN 'Kudamm 56'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%aladdin%') THEN 'Aladdin'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%vampire%') THEN 'Vampire'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%checkout%') THEN 'Checkout page'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%faq%') THEN 'FAQ'
      WHEN ( LOWER(  {{ page_path }}) = '/') THEN 'Home Page'
      WHEN ( LOWER(  {{ page_path }}) = '/home') THEN 'Home Page'
      WHEN ( LOWER(  {{ page_path }}) = '/tickets.html')THEN 'ticketonline/tickets'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%cast%')THEN 'Cast Page'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%/musicals-shows/%')THEN 'Musicals shows'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%sommer%')THEN 'Summer Shows'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%service%')THEN 'Service'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%/crm/%')THEN 'Calendar Pages'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%corporate-benefits%')THEN 'Corporate Benefits'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%404%')THEN '404 Error'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%stage-theater%' 
				OR LOWER(  {{ page_path }}) LIKE '%stage-theatertheatervermietung%' )THEN 'Stage Theater'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%ueber-uns%')THEN 'Abour Us'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%/indirekt/%')THEN 'Indirekt offer links'
      WHEN (LOWER(  {{ page_path }}) LIKE '%/vertriebsportal%'
      	OR LOWER(  {{ page_path }}) LIKE '%/theatervermietung%'
      	OR LOWER(  {{ page_path }}) LIKE '%/partner-vertrieb%') THEN 'For Company'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%/presse/%') THEN 'Press'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%/gutscheine/%')THEN 'Coupons'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%/disney-musicals%')THEN 'Disney Musicals'
      WHEN ( LOWER(  {{ page_path }}) LIKE '%/promotion%')THEN 'Promotion'
    ELSE
    'other'
  END
{% endmacro %}